name: tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Go to the lib dir
        run: |
          cd clickup

      - name: Run test
        run: |
          go test